security:
  oauth2:
    resource:
       userInfoUri: http://localhost:8901/auth/user
       
server:
  port: 8085

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

        