version: '3.7'
services:
  fintech-configurationserver:
    image: jcabelloc/fintech-configurationserver:0.0.1-SNAPSHOT
    ports:
       - "8888:8888"
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres_prod"
      POSTGRES_PASSWORD: "postgres_prod"
      POSTGRES_DB:       "fintech_prod"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql    
  fintech-servicio-prestamo:
      image: jcabelloc/fintech-servicio-prestamo:0.0.1-SNAPSHOT
      ports:
        - "8080:8080"
      environment:
        PROFILE: "prod"
        CONFIGSERVER_URI: "http://fintech-configurationserver:8888"
        CONFIGSERVER_PORT:   "8888"
        DATABASESERVER_PORT: "5432"
