server:
  port: 5555

spring:
#  sleuth:
#     sampler:#      probability: 1
  zipkin:
    baseUrl:  http://localhost:9411
    
#Configuración de los niveles de log
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      pe.fintech: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: routes,filters
       
zuul:
  # ignored-services: 'serviciocliente'
  ignored-services: '*' 
  prefix:  /api
  routes:
    serviciocliente: /cliente/**
    servicioprestamo: /prestamo/**
    prestamoestatico:
      path: /prestamoestatico/**
      # url: http://servicioprestamo-estatico:8081
      serviceId: prestamoestatico
      
#ribbon:
#  eureka:#    enabled: false
    
prestamoestatico:
  ribbon:
    listofservers: http://servicioprestamo-estatico:8081, http://servicioprestamo-estatico:8082      
    
    
    
    
    
    
    
    