logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    pe.fintech: DEBUG

security:
  oauth2:
    resource:
       userInfoUri: http://localhost:8901/auth/user
    client:
      clientId: fintechapp
