version: '3.7'
services:
  fintech-eurekaserver:
     image:   jcabelloc/fintech-eurekaserver:0.0.1-SNAPSHOT
     ports:
       - "8761:8761"
  fintech-configurationserver:
    image: jcabelloc/fintech-configurationserver:0.0.1-SNAPSHOT
    ports:
       - "8888:8888"
    environment:
      EUREKASERVER_URI: "http://fintech-eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      ENCRYPT_KEY:       "MUYSECRETO"
  fintech-zuulserver:
    image: jcabelloc/fintech-zuulserver:0.0.1-SNAPSHOT
    ports:
      - "5555:5555"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      CONFIGSERVER_URI: "http://fintech-configurationserver:8888"
      EUREKASERVER_URI: "http://fintech-eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      DATABASESERVER_PORT:      "5432"
      CONFIGSERVER_PORT:        "8888"
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB:       "fintech"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql      
  fintech-servicio-prestamo:
      image: jcabelloc/fintech-servicio-prestamo:0.0.1-SNAPSHOT
      ports:
        - "8080:8080"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8080"
        CONFIGSERVER_URI: "http://fintech-configurationserver:8888"
        EUREKASERVER_URI: "http://fintech-eurekaserver:8761/eureka/"
        KAFKASERVER_URI: "kafkaserver"
        ZKSERVER_URI: "kafkaserver"
        EUREKASERVER_PORT:   "8761"
        CONFIGSERVER_PORT:   "8888"
        DATABASESERVER_PORT: "5432"
        KAFKASERVER_PORT:    "2181"
        REDIS_PORT:          "6379"
        
  fintech-servicio-cliente:
      image: jcabelloc/fintech-servicio-cliente:0.0.1-SNAPSHOT
      ports:
        - "8085:8085"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8085"
        CONFIGSERVER_URI: "http://fintech-configurationserver:8888"
        EUREKASERVER_URI: "http://fintech-eurekaserver:8761/eureka/"
        KAFKASERVER_URI: "kafkaserver"
        ZKSERVER_URI: "kafkaserver"        
        EUREKASERVER_PORT:   "8761"
        CONFIGSERVER_PORT:   "8888"
        DATABASESERVER_PORT: "5432"
        KAFKASERVER_PORT:    "2181"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  kafkaserver:
    image: johnnypark/kafka-zookeeper
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
        ADVERTISED_HOST: kafkaserver
        NUM_PARTITIONS: "10"
        